In [3]:
import pandas as pd

In [4]:
!ls

Dec22Kro_TOTAL_CurrentPenalty.csv
Fines_Kroger-AfterDropDuplicatestoEnd.ipynb
Fines_Kroger-toDropDuplicates.ipynb

In [5]:
df = pd.read_csv("Dec22Kro_TOTAL_CurrentPenalty.csv")
df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Note,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
0,0,1.621876e+06,09/14/2022,626700,TX,Planned,Partial,NaN,445110,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$2,796",$0,"$2,796",1.621876e+06
1,1,1.614916e+06,08/16/2022,316400,WV,Referral,Partial,NaN,445110,2,...,NaN,NaN,Current Penalty,"$24,862",$0,$0,$0,$0,"$24,862",1.614916e+06
2,2,1.613884e+06,08/09/2022,830600,CO,Complaint,Partial,NaN,424410,1,...,NaN,NaN,Current Penalty,$0,$0,$414,$0,$0,$414,1.613884e+06
3,3,1.590209e+06,04/13/2022,854910,UT,Complaint,Partial,NaN,493110,1,...,NaN,NaN,Current Penalty,"$2,250",$0,$0,$0,$0,"$2,250",1.590209e+06
4,4,1.589516e+06,04/12/2022,452110,KY,Complaint,Partial,5411.0,445110,1,...,NaN,NaN,Current Penalty,"$7,000",$0,$0,$0,$0,"$7,000",1.589516e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,169,3.143333e+08,04/16/2010,627100,AR,Complaint,Partial,5411.0,445110,1,...,NaN,NaN,Current Penalty,$840,$0,$0,$0,$0,$840,3.143333e+08
170,170,3.120076e+08,04/09/2010,552652,MI,Planned,Complete,5411.0,445110,9,...,NaN,Safety-Manufacturing,Current Penalty,"$1,300",$0,$0,$0,$0,"$1,300",3.120076e+08
171,171,3.120384e+08,04/01/2010,552652,MI,Complaint,Partial,5411.0,445110,1,...,NaN,Safety-Manufacturing,Current Penalty,$450,$0,$0,$0,$0,$450,3.120384e+08
172,172,3.138321e+08,03/15/2010,551800,IN,Accident,Partial,5411.0,445110,3,...,NaN,Safety-Manufacturing,Current Penalty,"$7,000",$0,$0,"$1,000",$0,"$8,000",3.138321e+08
173,173,3.131540e+08,02/12/2010,522500,OH,Complaint,Partial,5141.0,424410,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$2,000",$0,"$2,000",3.131540e+08

In [6]:
df = df.drop_duplicates(['Activity'])
df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Note,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
0,0,1.621876e+06,09/14/2022,626700,TX,Planned,Partial,NaN,445110,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$2,796",$0,"$2,796",1.621876e+06
1,1,1.614916e+06,08/16/2022,316400,WV,Referral,Partial,NaN,445110,2,...,NaN,NaN,Current Penalty,"$24,862",$0,$0,$0,$0,"$24,862",1.614916e+06
2,2,1.613884e+06,08/09/2022,830600,CO,Complaint,Partial,NaN,424410,1,...,NaN,NaN,Current Penalty,$0,$0,$414,$0,$0,$414,1.613884e+06
3,3,1.590209e+06,04/13/2022,854910,UT,Complaint,Partial,NaN,493110,1,...,NaN,NaN,Current Penalty,"$2,250",$0,$0,$0,$0,"$2,250",1.590209e+06
4,4,1.589516e+06,04/12/2022,452110,KY,Complaint,Partial,5411.0,445110,1,...,NaN,NaN,Current Penalty,"$7,000",$0,$0,$0,$0,"$7,000",1.589516e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,169,3.143333e+08,04/16/2010,627100,AR,Complaint,Partial,5411.0,445110,1,...,NaN,NaN,Current Penalty,$840,$0,$0,$0,$0,$840,3.143333e+08
170,170,3.120076e+08,04/09/2010,552652,MI,Planned,Complete,5411.0,445110,9,...,NaN,Safety-Manufacturing,Current Penalty,"$1,300",$0,$0,$0,$0,"$1,300",3.120076e+08
171,171,3.120384e+08,04/01/2010,552652,MI,Complaint,Partial,5411.0,445110,1,...,NaN,Safety-Manufacturing,Current Penalty,$450,$0,$0,$0,$0,$450,3.120384e+08
172,172,3.138321e+08,03/15/2010,551800,IN,Accident,Partial,5411.0,445110,3,...,NaN,Safety-Manufacturing,Current Penalty,"$7,000",$0,$0,"$1,000",$0,"$8,000",3.138321e+08
173,173,3.131540e+08,02/12/2010,522500,OH,Complaint,Partial,5141.0,424410,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$2,000",$0,"$2,000",3.131540e+08

In [7]:
df.to_csv('Dec22Kro_toDropDuplicates.csv', index=False)