In [3]:
import pandas as pd

In [4]:
!ls

Dec22DT_TOTAL_CurrentPenalty_master.csv
Fines_DollarTree-AfterDropDuplicatestoEnd.ipynb
Fines_DollarTree-toDropDuplicates.ipynb

In [5]:
df = pd.read_csv("Dec22DT_TOTAL_CurrentPenalty_master.csv")
df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
0,0,1616331.015,08/22/2022,453720,NC,Complaint,Partial,5331.0,452990,6,...,NaN,NaN,Current Penalty,$0,$0,"$42,000",$0,$0,"$42,000",1616331.015
1,1,1618010.015,08/10/2022,316400,WV,Complaint,Partial,NaN,452319,1,...,NaN,NaN,Current Penalty,"$6,215",$0,$0,$0,$0,"$6,215",1618010.015
2,2,1612868.015,08/05/2022,953210,NV,Referral,Partial,NaN,452319,1,...,NaN,NaN,Current Penalty,"$2,245",$0,$0,$0,$0,"$2,245",1612868.015
3,3,1611611.015,08/01/2022,1054111,OR,Complaint,Partial,5331.0,452990,5,...,NaN,NaN,Current Penalty,$0,$0,"$33,000",$0,$0,"$33,000",1611611.015
4,4,1610668.015,07/27/2022,1054111,OR,Complaint,Partial,5331.0,452990,1,...,NaN,NaN,Current Penalty,$0,$0,$0,$0,$0,$0,1610668.015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,552,1184357.015,10/18/2016,355124,VA,Complaint,Partial,NaN,452990,1,...,NaN,NaN,Current Penalty,$0,$0,$0,$0,$0,$0,1184357.015
553,553,1173557.015,08/24/2016,627100,AR,Complaint,Partial,NaN,493110,1,...,NaN,NaN,Current Penalty,"$12,471",$0,$0,$0,$0,"$12,471",1173557.015
554,554,1168125.015,08/05/2016,419400,MS,Complaint,Partial,NaN,452112,1,...,NaN,NaN,Current Penalty,"$2,526",$0,$0,$0,$0,"$2,526",1168125.015
555,555,1144592.015,04/29/2016,215800,NY,Referral,Complete,NaN,493110,4,...,NaN,NaN,Current Penalty,"$18,707",$0,$0,$0,$0,"$18,707",1144592.015
556,556,1133313.015,03/16/2016,112300,RI,Complaint,Partial,NaN,452990,3,...,NaN,NaN,Current Penalty,"$6,545",$0,$0,"$2,380",$0,"$8,925",1133313.015

In [6]:
df = df.drop_duplicates(['Activity'])
df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
0,0,1616331.015,08/22/2022,453720,NC,Complaint,Partial,5331.0,452990,6,...,NaN,NaN,Current Penalty,$0,$0,"$42,000",$0,$0,"$42,000",1616331.015
1,1,1618010.015,08/10/2022,316400,WV,Complaint,Partial,NaN,452319,1,...,NaN,NaN,Current Penalty,"$6,215",$0,$0,$0,$0,"$6,215",1618010.015
2,2,1612868.015,08/05/2022,953210,NV,Referral,Partial,NaN,452319,1,...,NaN,NaN,Current Penalty,"$2,245",$0,$0,$0,$0,"$2,245",1612868.015
3,3,1611611.015,08/01/2022,1054111,OR,Complaint,Partial,5331.0,452990,5,...,NaN,NaN,Current Penalty,$0,$0,"$33,000",$0,$0,"$33,000",1611611.015
4,4,1610668.015,07/27/2022,1054111,OR,Complaint,Partial,5331.0,452990,1,...,NaN,NaN,Current Penalty,$0,$0,$0,$0,$0,$0,1610668.015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,552,1184357.015,10/18/2016,355124,VA,Complaint,Partial,NaN,452990,1,...,NaN,NaN,Current Penalty,$0,$0,$0,$0,$0,$0,1184357.015
553,553,1173557.015,08/24/2016,627100,AR,Complaint,Partial,NaN,493110,1,...,NaN,NaN,Current Penalty,"$12,471",$0,$0,$0,$0,"$12,471",1173557.015
554,554,1168125.015,08/05/2016,419400,MS,Complaint,Partial,NaN,452112,1,...,NaN,NaN,Current Penalty,"$2,526",$0,$0,$0,$0,"$2,526",1168125.015
555,555,1144592.015,04/29/2016,215800,NY,Referral,Complete,NaN,493110,4,...,NaN,NaN,Current Penalty,"$18,707",$0,$0,$0,$0,"$18,707",1144592.015
556,556,1133313.015,03/16/2016,112300,RI,Complaint,Partial,NaN,452990,3,...,NaN,NaN,Current Penalty,"$6,545",$0,$0,"$2,380",$0,"$8,925",1133313.015

In [7]:
df.to_csv('Dec22DT_toDropDuplicates.csv', index=False)