In [32]:
import pandas as pd

In [33]:
!ls

1. Final-Scrape-DollarGeneral.ipynb    3. Drop duplicates.ipynb
1_DG_activities_df.csv                 4. Work2_MoreWork_Fines.ipynb
1_DG_details_df.csv                    5. Work2_MoreWork_Violations.ipynb
1_DG_investigated_inspections_df.csv   Jan16DG_CurrentFines.csv
1_DG_related_activity_df.csv           Jan16DG_Fines.csv
1_DG_violation_items_df.csv            Jan16DG_InitialFines.csv
1_DG_violation_summary_df.csv          Jan16DG_Violations.csv
2. Joining_dfs_Violation_Summary.ipynb Jan16DG_toDropDuplicates.csv
2_DG_final_df.csv

In [34]:
df = pd.read_csv("2_final_df.csv")
df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
0,0,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Initial Violations,NaN,2,NaN,NaN,NaN,2,1.619753e+06
1,1,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Current Violations,NaN,2,NaN,NaN,NaN,2,1.619753e+06
2,2,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Initial Penalty,$0,"$140,000",$0,$0,$0,"$140,000",1.619753e+06
3,3,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Current Penalty,$0,"$140,000",$0,$0,$0,"$140,000",1.619753e+06
4,4,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,FTA Penalty,$0,$0,$0,$0,$0,$0,1.619753e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1960,1960,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Initial Violations,1,NaN,NaN,5,NaN,6,3.140213e+08
1961,1961,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Current Violations,NaN,NaN,NaN,6,NaN,6,3.140213e+08
1962,1962,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Initial Penalty,"$2,750",$0,$0,$0,$0,"$2,750",3.140213e+08
1963,1963,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Current Penalty,$0,$0,$0,$975,$0,$975,3.140213e+08
1964,1964,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,FTA Penalty,$0,$0,$0,$0,$0,$0,3.140213e+08

In [35]:
Current_Penalty_df = df[df['Violations/Penalties'] == 'Current Penalty']
Current_Penalty_df = Current_Penalty_df.drop_duplicates(['Activity'])
Current_Penalty_df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
3,3,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Current Penalty,$0,"$140,000",$0,$0,$0,"$140,000",1.619753e+06
8,8,1.617010e+06,08/25/2022,552652,MI,Complaint,Partial,NaN,452319,1,...,NaN,NaN,Current Penalty,$0,$0,$0,$0,$0,$0,1.617010e+06
13,13,1.609906e+06,07/25/2022,454716,TN,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Current Penalty,$0,$0,"$6,750",$0,$0,"$6,750",1.609906e+06
18,18,1.607451e+06,07/13/2022,418100,GA,Complaint,Partial,NaN,445110,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$5,283",$0,"$5,283",1.607451e+06
23,23,1.601808e+06,06/14/2022,418400,GA,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Current Penalty,$0,$0,"$290,054",$0,$0,"$290,054",1.601808e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1943,1943,1.079844e+06,07/23/2015,419700,FL,Complaint,Partial,NaN,452990,2,...,NaN,NaN,Current Penalty,"$3,600",$0,$0,$0,$0,"$3,600",1.079844e+06
1948,1948,1.083884e+06,07/20/2015,418300,AL,Referral,Partial,NaN,452910,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$4,200",$0,"$4,200",1.083884e+06
1953,1953,1.062209e+06,05/11/2015,729300,MO,Complaint,Partial,NaN,452112,2,...,NaN,NaN,Current Penalty,$0,$0,"$27,500",$550,$0,"$28,050",1.062209e+06
1958,1958,3.167852e+08,08/14/2013,453710,NC,Complaint,Partial,5331.0,452990,2,...,NaN,Health-Manufacturing,Current Penalty,$0,$0,$0,$0,$0,$0,3.167852e+08
1963,1963,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Current Penalty,$0,$0,$0,$975,$0,$975,3.140213e+08

In [36]:
Initial_Penalty_df = df[df['Violations/Penalties'] == 'Initial Penalty']
Initial_Penalty_df = Initial_Penalty_df.drop_duplicates(['Activity'])
Initial_Penalty_df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
2,2,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Initial Penalty,$0,"$140,000",$0,$0,$0,"$140,000",1.619753e+06
7,7,1.617010e+06,08/25/2022,552652,MI,Complaint,Partial,NaN,452319,1,...,NaN,NaN,Initial Penalty,$0,$0,$0,$0,$0,$0,1.617010e+06
12,12,1.609906e+06,07/25/2022,454716,TN,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Initial Penalty,$0,$0,"$7,500",$0,$0,"$7,500",1.609906e+06
17,17,1.607451e+06,07/13/2022,418100,GA,Complaint,Partial,NaN,445110,1,...,NaN,NaN,Initial Penalty,"$5,283",$0,$0,$0,$0,"$5,283",1.607451e+06
22,22,1.601808e+06,06/14/2022,418400,GA,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Initial Penalty,$0,$0,"$290,054",$0,$0,"$290,054",1.601808e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1942,1942,1.079844e+06,07/23/2015,419700,FL,Complaint,Partial,NaN,452990,2,...,NaN,NaN,Initial Penalty,"$6,000",$0,$0,$0,$0,"$6,000",1.079844e+06
1947,1947,1.083884e+06,07/20/2015,418300,AL,Referral,Partial,NaN,452910,1,...,NaN,NaN,Initial Penalty,"$6,000",$0,$0,$0,$0,"$6,000",1.083884e+06
1952,1952,1.062209e+06,05/11/2015,729300,MO,Complaint,Partial,NaN,452112,2,...,NaN,NaN,Initial Penalty,$0,$0,"$55,000","$1,100",$0,"$56,100",1.062209e+06
1957,1957,3.167852e+08,08/14/2013,453710,NC,Complaint,Partial,5331.0,452990,2,...,NaN,Health-Manufacturing,Initial Penalty,$0,$0,$0,$0,$0,$0,3.167852e+08
1962,1962,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Initial Penalty,"$2,750",$0,$0,$0,$0,"$2,750",3.140213e+08

In [37]:
Current_Violations_df = df[df['Violations/Penalties'] == 'Current Violations']
Current_Violations_df = Current_Violations_df.drop_duplicates(['Activity'])
Current_Violations_df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
1,1,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Current Violations,NaN,2,NaN,NaN,NaN,2,1.619753e+06
6,6,1.617010e+06,08/25/2022,552652,MI,Complaint,Partial,NaN,452319,1,...,NaN,NaN,Current Violations,NaN,NaN,NaN,1,NaN,1,1.617010e+06
11,11,1.609906e+06,07/25/2022,454716,TN,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Current Violations,NaN,NaN,2,NaN,NaN,2,1.609906e+06
16,16,1.607451e+06,07/13/2022,418100,GA,Complaint,Partial,NaN,445110,1,...,NaN,NaN,Current Violations,NaN,NaN,NaN,1,NaN,1,1.607451e+06
21,21,1.601808e+06,06/14/2022,418400,GA,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Current Violations,NaN,NaN,2,NaN,NaN,2,1.601808e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1941,1941,1.079844e+06,07/23/2015,419700,FL,Complaint,Partial,NaN,452990,2,...,NaN,NaN,Current Violations,2,NaN,NaN,NaN,NaN,2,1.079844e+06
1946,1946,1.083884e+06,07/20/2015,418300,AL,Referral,Partial,NaN,452910,1,...,NaN,NaN,Current Violations,NaN,NaN,NaN,1,NaN,1,1.083884e+06
1951,1951,1.062209e+06,05/11/2015,729300,MO,Complaint,Partial,NaN,452112,2,...,NaN,NaN,Current Violations,NaN,NaN,1,1,NaN,2,1.062209e+06
1956,1956,3.167852e+08,08/14/2013,453710,NC,Complaint,Partial,5331.0,452990,2,...,NaN,Health-Manufacturing,Current Violations,NaN,NaN,NaN,2,NaN,2,3.167852e+08
1961,1961,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Current Violations,NaN,NaN,NaN,6,NaN,6,3.140213e+08

In [38]:
Initial_Violations_df = df[df['Violations/Penalties'] == 'Initial Violations']
Initial_Violations_df = Initial_Violations_df.drop_duplicates(['Activity'])
Initial_Violations_df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
0,0,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Initial Violations,NaN,2,NaN,NaN,NaN,2,1.619753e+06
5,5,1.617010e+06,08/25/2022,552652,MI,Complaint,Partial,NaN,452319,1,...,NaN,NaN,Initial Violations,NaN,NaN,NaN,1,NaN,1,1.617010e+06
10,10,1.609906e+06,07/25/2022,454716,TN,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Initial Violations,NaN,NaN,2,NaN,NaN,2,1.609906e+06
15,15,1.607451e+06,07/13/2022,418100,GA,Complaint,Partial,NaN,445110,1,...,NaN,NaN,Initial Violations,1,NaN,NaN,NaN,NaN,1,1.607451e+06
20,20,1.601808e+06,06/14/2022,418400,GA,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Initial Violations,NaN,NaN,2,NaN,NaN,2,1.601808e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1940,1940,1.079844e+06,07/23/2015,419700,FL,Complaint,Partial,NaN,452990,2,...,NaN,NaN,Initial Violations,2,NaN,NaN,NaN,NaN,2,1.079844e+06
1945,1945,1.083884e+06,07/20/2015,418300,AL,Referral,Partial,NaN,452910,1,...,NaN,NaN,Initial Violations,1,NaN,NaN,NaN,NaN,1,1.083884e+06
1950,1950,1.062209e+06,05/11/2015,729300,MO,Complaint,Partial,NaN,452112,2,...,NaN,NaN,Initial Violations,NaN,NaN,1,1,NaN,2,1.062209e+06
1955,1955,3.167852e+08,08/14/2013,453710,NC,Complaint,Partial,5331.0,452990,2,...,NaN,Health-Manufacturing,Initial Violations,NaN,NaN,NaN,2,NaN,2,3.167852e+08
1960,1960,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Initial Violations,1,NaN,NaN,5,NaN,6,3.140213e+08

In [39]:
Current_Penalty_df.to_csv('3_currentpenaltydrop.csv', index=False)

In [40]:
Initial_Penalty_df.to_csv('3_initialpenaltydrop.csv', index=False)

In [41]:
Current_Violations_df.to_csv('3_currentviolationsdrop.csv', index=False)

In [42]:
Initial_Violations_df.to_csv('3_initialviolationsdrop.csv', index=False)