In [1]:
import pandas as pd

In [2]:
!ls

Dec22DG_activities_df.csv
Dec22DG_details_df.csv
Dec22DG_investigated_inspections_df.csv
Dec22DG_related_activity_df.csv
Dec22DG_TOTAL_master.csv
Dec22DG_violation_items_df.csv
Dec22DG_violation_summary_df.csv
Final-Scrape-DollarGeneral.ipynb
Fines_DG-AfterDropDuplicatestoEnd.ipynb
Fines_DG-toDropDuplicates.ipynb
Joining_dfs_DG-Final.ipynb

In [3]:
df = pd.read_csv("Dec22DG_TOTAL_master.csv")
df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
0,0,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Current Penalty,$0,"$140,000",$0,$0,$0,"$140,000",1.619753e+06
1,1,1.617010e+06,08/25/2022,552652,MI,Complaint,Partial,NaN,452319,1,...,NaN,NaN,Current Penalty,$0,$0,$0,$0,$0,$0,1.617010e+06
2,2,1.609906e+06,07/25/2022,454716,TN,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Current Penalty,$0,$0,"$6,750",$0,$0,"$6,750",1.609906e+06
3,3,1.607451e+06,07/13/2022,418100,GA,Complaint,Partial,NaN,445110,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$5,283",$0,"$5,283",1.607451e+06
4,4,1.601808e+06,06/14/2022,418400,GA,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Current Penalty,$0,$0,"$290,054",$0,$0,"$290,054",1.601808e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,387,1.079844e+06,07/23/2015,419700,FL,Complaint,Partial,NaN,452990,2,...,NaN,NaN,Current Penalty,"$3,600",$0,$0,$0,$0,"$3,600",1.079844e+06
388,388,1.083884e+06,07/20/2015,418300,AL,Referral,Partial,NaN,452910,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$4,200",$0,"$4,200",1.083884e+06
389,389,1.062209e+06,05/11/2015,729300,MO,Complaint,Partial,NaN,452112,2,...,NaN,NaN,Current Penalty,$0,$0,"$27,500",$550,$0,"$28,050",1.062209e+06
390,390,3.167852e+08,08/14/2013,453710,NC,Complaint,Partial,5331.0,452990,2,...,NaN,Health-Manufacturing,Current Penalty,$0,$0,$0,$0,$0,$0,3.167852e+08
391,391,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Current Penalty,$0,$0,$0,$975,$0,$975,3.140213e+08

In [4]:
df = df.drop_duplicates(['Activity'])
df

,Unnamed: 0,Activity,Opened,RID,St,Type,Sc,SIC_x,NAICS_x,Vio,...,Keywords,Planning Guide,Violations/Penalties,Serious,Willful,Repeat,Other,Unclass,Total,activity_code_y
0,0,1.619753e+06,09/06/2022,452110,KY,Complaint,Partial,4225.0,493110,2,...,NaN,NaN,Current Penalty,$0,"$140,000",$0,$0,$0,"$140,000",1.619753e+06
1,1,1.617010e+06,08/25/2022,552652,MI,Complaint,Partial,NaN,452319,1,...,NaN,NaN,Current Penalty,$0,$0,$0,$0,$0,$0,1.617010e+06
2,2,1.609906e+06,07/25/2022,454716,TN,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Current Penalty,$0,$0,"$6,750",$0,$0,"$6,750",1.609906e+06
3,3,1.607451e+06,07/13/2022,418100,GA,Complaint,Partial,NaN,445110,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$5,283",$0,"$5,283",1.607451e+06
4,4,1.601808e+06,06/14/2022,418400,GA,Complaint,Partial,NaN,452319,2,...,NaN,NaN,Current Penalty,$0,$0,"$290,054",$0,$0,"$290,054",1.601808e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,387,1.079844e+06,07/23/2015,419700,FL,Complaint,Partial,NaN,452990,2,...,NaN,NaN,Current Penalty,"$3,600",$0,$0,$0,$0,"$3,600",1.079844e+06
388,388,1.083884e+06,07/20/2015,418300,AL,Referral,Partial,NaN,452910,1,...,NaN,NaN,Current Penalty,$0,$0,$0,"$4,200",$0,"$4,200",1.083884e+06
389,389,1.062209e+06,05/11/2015,729300,MO,Complaint,Partial,NaN,452112,2,...,NaN,NaN,Current Penalty,$0,$0,"$27,500",$550,$0,"$28,050",1.062209e+06
390,390,3.167852e+08,08/14/2013,453710,NC,Complaint,Partial,5331.0,452990,2,...,NaN,Health-Manufacturing,Current Penalty,$0,$0,$0,$0,$0,$0,3.167852e+08
391,391,3.140213e+08,01/14/2010,453730,NC,Planned,Complete,5311.0,452112,6,...,NaN,Safety-Manufacturing,Current Penalty,$0,$0,$0,$975,$0,$975,3.140213e+08

In [6]:
df.to_csv('Dec22DG_toDropDuplicates.csv', index=False)